import { PlayerSaveData } from "./save-types"

/**
 * Legendary Players Data
 * Phase 23: Hall of Fame
 * 
 * Full player profiles for founding legends.
 * These are added to the players array at game start as retired legends.
 */
export const LEGENDARY_PLAYERS: PlayerSaveData[] = [
    {
        id: "legend_sovran",
        name: "Axel Sund",
        nickname: "Sovran",
        age: 34,
        nationality: "SE",
        portraitPath: "/assets/legends/Sovran.svg",
        role: "Rifler",
        tier: "ELITE",

        // Elite Stats (98 OVR)
        skill: 98,
        awp: 65,
        rifle: 96,
        pistol: 88,
        grenades: 92,
        creativity: 95,
        clutch: 98,
        tactic: 90,
        leader: 75,
        teamwork: 94,
        morale: 90,
        amicability: 85,
        productivity: 88,
        stressResistance: 95,
        loyalty: 90,
        reaction: 88,
        eyesight: 92,
        health: 75,
        strength: 70,
        endurance: 78,

        // Dynamic
        form: 85,
        fatigue: 0,
        potential: 98,

        // Career (Legendary)
        matchesPlayed: 1247,
        roundsPlayed: 28450,
        avgRating: 1.28,
        clutchSuccessRate: 71,
        totalKills: 24893,
        totalDeaths: 18420,
        totalMVPs: 21,
        majorWins: 2,

        // Status
        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["2x Major Champion", "87 Consecutive LAN Maps", "Best Player 2013-2014"],
        careerTeams: ["Nova Invaders", "Dignity"],
        proHistory: [
            { year: 2013, rank: 1 },
            { year: 2014, rank: 1 },
            { year: 2015, rank: 8 },
            { year: 2016, rank: 12 }
        ],
        prestigeScore: 98,
        perks: ["clutch_king", "lurk_master", "spray_control"],
        roleMastery: { "Rifler": 98, "Lurker": 95 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_ironbark",
        name: "Patrik Lundborg",
        nickname: "Ironbark",
        age: 36,
        nationality: "SE",
        portraitPath: "/assets/legends/Ironbark.svg",
        role: "Rifler",
        tier: "ELITE",

        skill: 97,
        awp: 72,
        rifle: 95,
        pistol: 90,
        grenades: 94,
        creativity: 93,
        clutch: 92,
        tactic: 88,
        leader: 70,
        teamwork: 92,
        morale: 88,
        amicability: 90,
        productivity: 85,
        stressResistance: 92,
        loyalty: 88,
        reaction: 85,
        eyesight: 90,
        health: 72,
        strength: 68,
        endurance: 75,

        form: 82,
        fatigue: 0,
        potential: 97,

        matchesPlayed: 1489,
        roundsPlayed: 34200,
        avgRating: 1.26,
        clutchSuccessRate: 63,
        totalKills: 29450,
        totalDeaths: 22100,
        totalMVPs: 18,
        majorWins: 2,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["2x Major Champion", "20+ Year Career", "Longevity Icon"],
        careerTeams: ["Nova Invaders", "Dignity", "FATEBOUND"],
        proHistory: [
            { year: 2010, rank: 2 },
            { year: 2013, rank: 3 },
            { year: 2014, rank: 4 },
            { year: 2015, rank: 15 }
        ],
        prestigeScore: 97,
        perks: ["rifle_god", "consistency_king", "veteran"],
        roleMastery: { "Rifler": 97, "Secondary AWP": 72 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_nocturn",
        name: "Kenneth Schreb",
        nickname: "Nocturn",
        age: 29,
        nationality: "FR",
        portraitPath: "/assets/legends/Nocturn.svg",
        role: "AWPer, Rifler",
        tier: "ELITE",

        skill: 94,
        awp: 99,
        rifle: 78,
        pistol: 82,
        grenades: 72,
        creativity: 88,
        clutch: 88,
        tactic: 75,
        leader: 55,
        teamwork: 80,
        morale: 82,
        amicability: 78,
        productivity: 80,
        stressResistance: 85,
        loyalty: 75,
        reaction: 95,
        eyesight: 98,
        health: 85,
        strength: 72,
        endurance: 80,

        form: 80,
        fatigue: 0,
        potential: 94,

        matchesPlayed: 1156,
        roundsPlayed: 26800,
        avgRating: 1.24,
        clutchSuccessRate: 65,
        totalKills: 22340,
        totalDeaths: 17890,
        totalMVPs: 15,
        majorWins: 1,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Major Champion", "AWP Meta Definer", "Major MVP"],
        careerTeams: ["G-Two", "Envira", "Titan"],
        proHistory: [
            { year: 2014, rank: 3 },
            { year: 2015, rank: 6 },
            { year: 2017, rank: 9 }
        ],
        prestigeScore: 94,
        perks: ["awp_god", "flick_master", "aggressive_awp"],
        roleMastery: { "AWPer": 99 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_varden",
        name: "Olaf Kajberg",
        nickname: "Varden",
        age: 32,
        nationality: "SE",
        portraitPath: "/assets/legends/Varden.svg",
        role: "Rifler, Entry",
        tier: "ELITE",

        skill: 92,
        awp: 68,
        rifle: 92,
        pistol: 88,
        grenades: 89,
        creativity: 90,
        clutch: 91,
        tactic: 85,
        leader: 65,
        teamwork: 90,
        morale: 85,
        amicability: 88,
        productivity: 82,
        stressResistance: 88,
        loyalty: 85,
        reaction: 88,
        eyesight: 90,
        health: 78,
        strength: 72,
        endurance: 80,

        form: 78,
        fatigue: 0,
        potential: 92,

        matchesPlayed: 1089,
        roundsPlayed: 25100,
        avgRating: 1.22,
        clutchSuccessRate: 68,
        totalKills: 20780,
        totalDeaths: 16890,
        totalMVPs: 12,
        majorWins: 2,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["2x Major Champion", "Best Player 2015", "Olofpass"],
        careerTeams: ["phanatic", "Phaze", "FATEBOUND"],
        proHistory: [
            { year: 2015, rank: 1 },
            { year: 2016, rank: 7 },
            { year: 2018, rank: 14 }
        ],
        prestigeScore: 92,
        perks: ["clutch_king", "versatile", "big_game_player"],
        roleMastery: { "Rifler": 92, "Support": 85 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_bastion",
        name: "Jarek Jakob",
        nickname: "Bastion",
        age: 36,
        nationality: "PL",
        portraitPath: "/assets/legends/Bastion.svg",
        role: "Rifler",
        tier: "PRO",

        skill: 88,
        awp: 58,
        rifle: 84,
        pistol: 80,
        grenades: 79,
        creativity: 75,
        clutch: 85,
        tactic: 72,
        leader: 70,
        teamwork: 90,
        morale: 95,
        amicability: 98,
        productivity: 78,
        stressResistance: 88,
        loyalty: 95,
        reaction: 82,
        eyesight: 85,
        health: 90,
        strength: 95,
        endurance: 88,

        form: 75,
        fatigue: 0,
        potential: 88,

        matchesPlayed: 987,
        roundsPlayed: 22800,
        avgRating: 1.12,
        clutchSuccessRate: 59,
        totalKills: 18450,
        totalDeaths: 16200,
        totalMVPs: 5,
        majorWins: 1,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Major Champion", "Cultural Icon", "Eastern European Legend"],
        careerTeams: ["Virtus Nova"],
        proHistory: [
            { year: 2014, rank: 12 },
            { year: 2015, rank: 18 },
            { year: 2017, rank: 20 }
        ],
        prestigeScore: 88,
        perks: ["fan_favorite", "team_spirit", "never_give_up"],
        roleMastery: { "Rifler": 84, "Support": 80 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_krolon",
        name: "Dany Telsen",
        nickname: "Krolon",
        age: 36,
        nationality: "UA",
        portraitPath: "/assets/legends/Krolon.svg",
        role: "IGL, Support",
        tier: "PRO",

        skill: 87,
        awp: 45,
        rifle: 72,
        pistol: 70,
        grenades: 95,
        creativity: 78,
        clutch: 82,
        tactic: 98,
        leader: 99,
        teamwork: 95,
        morale: 90,
        amicability: 82,
        productivity: 85,
        stressResistance: 92,
        loyalty: 90,
        reaction: 75,
        eyesight: 78,
        health: 80,
        strength: 75,
        endurance: 82,

        form: 72,
        fatigue: 0,
        potential: 87,

        matchesPlayed: 1245,
        roundsPlayed: 28900,
        avgRating: 1.08,
        clutchSuccessRate: 55,
        totalKills: 20100,
        totalDeaths: 19800,
        totalMVPs: 3,
        majorWins: 1,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Major Champion", "Legendary IGL", "Roster Architect"],
        careerTeams: ["Natus Vincera", "Gambyt"],
        proHistory: [
            { year: 2010, rank: 8 },
            { year: 2017, rank: 15 },
            { year: 2018, rank: 18 }
        ],
        prestigeScore: 87,
        perks: ["mastermind", "tactical_genius", "mentor"],
        roleMastery: { "IGL": 99, "Support": 85 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_v4ltz",
        name: "Aleksander Kostev",
        nickname: "V4ltz",
        age: 27,
        nationality: "UA",
        portraitPath: "/assets/legends/V4ltz.svg",
        role: "AWPer, Rifler",
        tier: "ELITE",

        skill: 99,
        awp: 99,
        rifle: 97,
        pistol: 95,
        grenades: 88,
        creativity: 98,
        clutch: 97,
        tactic: 85,
        leader: 70,
        teamwork: 82,
        morale: 85,
        amicability: 70,
        productivity: 90,
        stressResistance: 92,
        loyalty: 88,
        reaction: 99,
        eyesight: 99,
        health: 92,
        strength: 78,
        endurance: 88,

        form: 95,
        fatigue: 0,
        potential: 99,

        matchesPlayed: 1350,
        roundsPlayed: 31200,
        avgRating: 1.35,
        clutchSuccessRate: 72,
        totalKills: 28900,
        totalDeaths: 19200,
        totalMVPs: 28,
        majorWins: 1,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Major Champion 2021", "4x Player of the Year", "Greatest of All Time"],
        careerTeams: ["Natus Vincera", "Team Tide", "Flipside3"],
        proHistory: [
            { year: 2018, rank: 1 },
            { year: 2019, rank: 2 },
            { year: 2021, rank: 1 },
            { year: 2022, rank: 1 }
        ],
        prestigeScore: 99,
        perks: ["awp_god", "clutch_king", "carry_potential"],
        roleMastery: { "AWPer": 99, "Rifler": 97 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_kalvera",
        name: "Niklas Reedt",
        nickname: "Kalvera",
        age: 29,
        nationality: "DK",
        portraitPath: "/assets/legends/Kalvera.svg",
        role: "AWPer",
        tier: "ELITE",

        skill: 96,
        awp: 98,
        rifle: 85,
        pistol: 88,
        grenades: 85,
        creativity: 82,
        clutch: 90,
        tactic: 90,
        leader: 65,
        teamwork: 95,
        morale: 88,
        amicability: 90,
        productivity: 92,
        stressResistance: 95,
        loyalty: 85,
        reaction: 94,
        eyesight: 97,
        health: 75,
        strength: 70,
        endurance: 78,

        form: 88,
        fatigue: 0,
        potential: 96,

        matchesPlayed: 1280,
        roundsPlayed: 29600,
        avgRating: 1.22,
        clutchSuccessRate: 67,
        totalKills: 24500,
        totalDeaths: 18900,
        totalMVPs: 20,
        majorWins: 4,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["4x Major Champion", "Most Consistent AWPer", "Grand Slam"],
        careerTeams: ["Astraflux", "Nova Invaders", "Dignity"],
        proHistory: [
            { year: 2016, rank: 4 },
            { year: 2018, rank: 3 },
            { year: 2019, rank: 4 },
            { year: 2020, rank: 6 }
        ],
        prestigeScore: 96,
        perks: ["consistency_king", "major_specialist", "tactical_awp"],
        roleMastery: { "AWPer": 98 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_niklaus",
        name: "Nikolai Kovich",
        nickname: "Niklaus",
        age: 27,
        nationality: "BA",
        portraitPath: "/assets/legends/Niklaus.svg",
        role: "Rifler, Entry",
        tier: "ELITE",

        skill: 98,
        awp: 82,
        rifle: 99,
        pistol: 95,
        grenades: 85,
        creativity: 95,
        clutch: 94,
        tactic: 82,
        leader: 75,
        teamwork: 80,
        morale: 85,
        amicability: 75,
        productivity: 88,
        stressResistance: 88,
        loyalty: 78,
        reaction: 97,
        eyesight: 96,
        health: 88,
        strength: 75,
        endurance: 85,

        form: 90,
        fatigue: 0,
        potential: 98,

        matchesPlayed: 1180,
        roundsPlayed: 27300,
        avgRating: 1.28,
        clutchSuccessRate: 69,
        totalKills: 25200,
        totalDeaths: 18100,
        totalMVPs: 18,
        majorWins: 0,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Global Top 3 Multiple Years", "Best Aimer Ever", "Superstar"],
        careerTeams: ["Phaze Syndicate", "G-Two", "Mousen Sports"],
        proHistory: [
            { year: 2017, rank: 3 },
            { year: 2018, rank: 5 },
            { year: 2020, rank: 4 },
            { year: 2021, rank: 5 }
        ],
        prestigeScore: 98,
        perks: ["aim_god", "deagle_master", "mechanical_genius"],
        roleMastery: { "Rifler": 99, "Entry": 90 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_frosthaven",
        name: "Marco Davis",
        nickname: "Frosthaven",
        age: 30,
        nationality: "BR",
        portraitPath: "/assets/legends/Frosthaven.svg",
        role: "Rifler, AWPer",
        tier: "ELITE",

        skill: 96,
        awp: 85,
        rifle: 96,
        pistol: 90,
        grenades: 82,
        creativity: 92,
        clutch: 98,
        tactic: 88,
        leader: 68,
        teamwork: 88,
        morale: 82,
        amicability: 75,
        productivity: 85,
        stressResistance: 95,
        loyalty: 75,
        reaction: 94,
        eyesight: 95,
        health: 85,
        strength: 72,
        endurance: 82,

        form: 82,
        fatigue: 0,
        potential: 96,

        matchesPlayed: 1050,
        roundsPlayed: 24300,
        avgRating: 1.24,
        clutchSuccessRate: 74,
        totalKills: 21800,
        totalDeaths: 16500,
        totalMVPs: 16,
        majorWins: 2,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["2x Major Champion", "2x Player of the Year", "Jumping Double Kill"],
        careerTeams: ["SC Gaming", "MB Esports", "Phaze Syndicate"],
        proHistory: [
            { year: 2016, rank: 1 },
            { year: 2017, rank: 1 },
            { year: 2018, rank: 8 },
            { year: 2019, rank: 11 }
        ],
        prestigeScore: 96,
        perks: ["clutch_king", "cold_blooded", "positioning_master"],
        roleMastery: { "Rifler": 96, "Lurker": 90 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_pyren",
        name: "Gabriel Tolmor",
        nickname: "Pyren",
        age: 33,
        nationality: "BR",
        portraitPath: "/assets/legends/Pyren.svg",
        role: "IGL, AWPer",
        tier: "ELITE",

        skill: 92,
        awp: 95,
        rifle: 78,
        pistol: 82,
        grenades: 90,
        creativity: 85,
        clutch: 88,
        tactic: 98,
        leader: 99,
        teamwork: 95,
        morale: 92,
        amicability: 95,
        productivity: 88,
        stressResistance: 92,
        loyalty: 95,
        reaction: 88,
        eyesight: 92,
        health: 82,
        strength: 75,
        endurance: 85,

        form: 80,
        fatigue: 0,
        potential: 92,

        matchesPlayed: 1320,
        roundsPlayed: 30500,
        avgRating: 1.15,
        clutchSuccessRate: 62,
        totalKills: 23100,
        totalDeaths: 20200,
        totalMVPs: 10,
        majorWins: 2,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["2x Major Champion", "Brazilian CS Godfather", "Legendary IGL"],
        careerTeams: ["SC Gaming", "MB Esports", "Tide", "Imperius"],
        proHistory: [
            { year: 2016, rank: 5 },
            { year: 2017, rank: 6 },
            { year: 2018, rank: 16 }
        ],
        prestigeScore: 92,
        perks: ["mastermind", "awp_igl", "mentor"],
        roleMastery: { "IGL": 99, "AWPer": 95 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_sentryx",
        name: "Ladis Kovalko",
        nickname: "Sentryx",
        age: 33,
        nationality: "SK",
        portraitPath: "/assets/legends/Sentryx.svg",
        role: "AWPer",
        tier: "ELITE",

        skill: 93,
        awp: 98,
        rifle: 72,
        pistol: 78,
        grenades: 75,
        creativity: 80,
        clutch: 88,
        tactic: 78,
        leader: 60,
        teamwork: 85,
        morale: 80,
        amicability: 82,
        productivity: 78,
        stressResistance: 85,
        loyalty: 80,
        reaction: 92,
        eyesight: 96,
        health: 75,
        strength: 70,
        endurance: 75,

        form: 75,
        fatigue: 0,
        potential: 93,

        matchesPlayed: 1150,
        roundsPlayed: 26600,
        avgRating: 1.18,
        clutchSuccessRate: 60,
        totalKills: 22400,
        totalDeaths: 18900,
        totalMVPs: 11,
        majorWins: 0,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["CIS AWP Legend", "Global Top 5 Multiple Years", "Eastern Europe Star"],
        careerTeams: ["Natus Vincera", "Phaze Syndicate", "Virtus Nova"],
        proHistory: [
            { year: 2015, rank: 4 },
            { year: 2016, rank: 6 },
            { year: 2017, rank: 11 }
        ],
        prestigeScore: 93,
        perks: ["awp_god", "cis_legend", "precision_master"],
        roleMastery: { "AWPer": 98 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_mirage",
        name: "Robin Ronnborg",
        nickname: "Mirage",
        age: 31,
        nationality: "SE",
        portraitPath: "/assets/legends/Mirage.svg",
        role: "Rifler, Support",
        tier: "ELITE",

        skill: 91,
        awp: 55,
        rifle: 90,
        pistol: 85,
        grenades: 88,
        creativity: 92,
        clutch: 95,
        tactic: 92,
        leader: 82,
        teamwork: 92,
        morale: 85,
        amicability: 80,
        productivity: 85,
        stressResistance: 95,
        loyalty: 85,
        reaction: 85,
        eyesight: 88,
        health: 82,
        strength: 75,
        endurance: 82,

        form: 78,
        fatigue: 0,
        potential: 91,

        matchesPlayed: 1180,
        roundsPlayed: 27300,
        avgRating: 1.14,
        clutchSuccessRate: 70,
        totalKills: 20800,
        totalDeaths: 17900,
        totalMVPs: 9,
        majorWins: 3,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["3x Major Champion", "Clutch Master", "Franchise Legend"],
        careerTeams: ["phanatic", "FATEBOUND", "Cumulus9"],
        proHistory: [
            { year: 2014, rank: 5 },
            { year: 2015, rank: 5 },
            { year: 2016, rank: 11 }
        ],
        prestigeScore: 91,
        perks: ["clutch_king", "game_sense", "big_brain"],
        roleMastery: { "Rifler": 90, "Support": 88 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_dupren",
        name: "Peter Rasmund",
        nickname: "Dupren",
        age: 31,
        nationality: "DK",
        portraitPath: "/assets/legends/Dupren.svg",
        role: "Entry, Rifler",
        tier: "ELITE",

        skill: 93,
        awp: 65,
        rifle: 94,
        pistol: 90,
        grenades: 88,
        creativity: 85,
        clutch: 85,
        tactic: 88,
        leader: 70,
        teamwork: 95,
        morale: 92,
        amicability: 95,
        productivity: 90,
        stressResistance: 90,
        loyalty: 92,
        reaction: 92,
        eyesight: 90,
        health: 85,
        strength: 78,
        endurance: 88,

        form: 82,
        fatigue: 0,
        potential: 93,

        matchesPlayed: 1240,
        roundsPlayed: 28700,
        avgRating: 1.16,
        clutchSuccessRate: 62,
        totalKills: 23500,
        totalDeaths: 19200,
        totalMVPs: 12,
        majorWins: 4,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["4x Major Champion", "Best Entry Fragger", "Northern Core"],
        careerTeams: ["Astraflux", "Vitalis", "Dignity"],
        proHistory: [
            { year: 2018, rank: 9 },
            { year: 2019, rank: 8 },
            { year: 2020, rank: 10 }
        ],
        prestigeScore: 93,
        perks: ["entry_master", "team_player", "major_specialist"],
        roleMastery: { "Entry": 94, "Rifler": 92 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_cipherx",
        name: "Andrej Hojsten",
        nickname: "Cipherx",
        age: 29,
        nationality: "DK",
        portraitPath: "/assets/legends/Cipherx.svg",
        role: "Support, Rifler",
        tier: "ELITE",

        skill: 90,
        awp: 55,
        rifle: 88,
        pistol: 85,
        grenades: 95,
        creativity: 82,
        clutch: 99,
        tactic: 92,
        leader: 65,
        teamwork: 98,
        morale: 88,
        amicability: 92,
        productivity: 88,
        stressResistance: 98,
        loyalty: 95,
        reaction: 85,
        eyesight: 88,
        health: 82,
        strength: 72,
        endurance: 85,

        form: 80,
        fatigue: 0,
        potential: 90,

        matchesPlayed: 1200,
        roundsPlayed: 27800,
        avgRating: 1.10,
        clutchSuccessRate: 78,
        totalKills: 20100,
        totalDeaths: 18200,
        totalMVPs: 8,
        majorWins: 4,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["4x Major Champion", "Clutch Minister", "Best Support"],
        careerTeams: ["Astraflux", "Dignity"],
        proHistory: [
            { year: 2018, rank: 12 },
            { year: 2019, rank: 14 }
        ],
        prestigeScore: 90,
        perks: ["clutch_king", "utility_master", "team_backbone"],
        roleMastery: { "Support": 98, "Rifler": 88 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    },
    {
        id: "legend_shoen",
        name: "Rikard Papillotte",
        nickname: "Shoen",
        age: 32,
        nationality: "FR",
        portraitPath: "/assets/legends/Shoen.svg",
        role: "Rifler, IGL",
        tier: "ELITE",

        skill: 93,
        awp: 72,
        rifle: 94,
        pistol: 90,
        grenades: 82,
        creativity: 95,
        clutch: 90,
        tactic: 85,
        leader: 85,
        teamwork: 85,
        morale: 80,
        amicability: 78,
        productivity: 82,
        stressResistance: 85,
        loyalty: 78,
        reaction: 90,
        eyesight: 92,
        health: 78,
        strength: 72,
        endurance: 80,

        form: 78,
        fatigue: 0,
        potential: 93,

        matchesPlayed: 1280,
        roundsPlayed: 29600,
        avgRating: 1.18,
        clutchSuccessRate: 65,
        totalKills: 24200,
        totalDeaths: 19800,
        totalMVPs: 14,
        majorWins: 1,

        isRetired: true,
        retirementWeek: 0,
        isLegendary: true,
        legendaryAchievements: ["Major Champion", "French Legend", "Style Icon"],
        careerTeams: ["G-Two", "Vitalis", "Envira", "Apex Games"],
        proHistory: [
            { year: 2013, rank: 5 },
            { year: 2016, rank: 5 },
            { year: 2017, rank: 8 }
        ],
        prestigeScore: 93,
        perks: ["flashy_plays", "french_legend", "versatile"],
        roleMastery: { "Rifler": 94, "IGL": 85 },
        availableSkillPoints: 0,
        energy: 100,
        maxEnergy: 100,
        level: 30,
        xp: 0,
        xpToNextLevel: 1000,
        talentPoints: 0,
        unlockedTalentIds: []
    }
]
