// Auto-generated by scripts/import-staff.js
import { StaffSaveData } from "./save-types";

export const REAL_STAFF_POOL: Partial<StaffSaveData>[] = [
  {
    "id": "real_coach_zonic",
    "name": "zonic",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/zonic.png",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 95,
      "development": 50,
      "leadership": 92
    }
  },
  {
    "id": "real_coach_xizt",
    "name": "Xizt",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Sweden",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/Xizt.png",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 90,
      "development": 50,
      "leadership": 88
    }
  },
  {
    "id": "real_coach_saw",
    "name": "sAw",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Finland",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/sAw.png",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 88,
      "development": 50,
      "leadership": 86
    }
  },
  {
    "id": "real_coach_daps",
    "name": "daps",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Canada",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/daps.png",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 85,
      "development": 50,
      "leadership": 84
    }
  },
  {
    "id": "real_coach_hunden",
    "name": "HUNDEN",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/HUNDEN.png",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 87,
      "development": 50,
      "leadership": 80
    }
  },
  {
    "id": "real_coach_emi",
    "name": "emi",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/emi.png",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "manManagement": 50,
      "tactical": 70,
      "development": 50,
      "leadership": 60
    }
  },
  {
    "id": "real_coach_rejin",
    "name": "Rejin",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/Rejin.png",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "manManagement": 50,
      "tactical": 72,
      "development": 50,
      "leadership": 58
    }
  },
  {
    "id": "real_coach_xtqzzz",
    "name": "XTQZZZ",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "France",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/XTQZZZ.png",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 92,
      "development": 50,
      "leadership": 90
    }
  },
  {
    "id": "real_coach_b1ad3",
    "name": "B1ad3",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Ukraine",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/B1ad3.png",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 96,
      "development": 50,
      "leadership": 88
    }
  },
  {
    "id": "real_coach_robban",
    "name": "RobbaN",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Sweden",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/RobbaN.png",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 94,
      "development": 50,
      "leadership": 92
    }
  },
  {
    "id": "real_coach_mithr",
    "name": "mithR",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/mithR.png",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 85,
      "development": 50,
      "leadership": 84
    }
  },
  {
    "id": "real_coach_kassad",
    "name": "kassad",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Known for balanced play",
    "portraitPath": "/assets/staff/coaches/kassad.png",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 86,
      "development": 50,
      "leadership": 82
    }
  },
  {
    "id": "real_analyst_spunj",
    "name": "SPUNJ",
    "role": "analyst",
    "level": 4,
    "specialization": "Macro & Meta",
    "salaryPerWeek": 2000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Australia",
    "description": "HLTV Confirmed, ex-pro",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "analysis": 95,
      "metaReading": 94,
      "prep": 90
    }
  },
  {
    "id": "real_analyst_thorin",
    "name": "Thorin",
    "role": "analyst",
    "level": 3,
    "specialization": "Narrative & History",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "UK",
    "description": "Esports journalism",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "analysis": 64,
      "metaReading": 45,
      "prep": 25
    }
  },
  {
    "id": "real_analyst_moses",
    "name": "Moses",
    "role": "analyst",
    "level": 4,
    "specialization": "Strategy",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "USA",
    "description": "Tactical casting",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 88,
      "metaReading": 86,
      "prep": 84
    }
  },
  {
    "id": "real_analyst_semmler",
    "name": "Semmler",
    "role": "analyst",
    "level": 4,
    "specialization": "Macro Analysis",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Veteran analyst",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 85,
      "metaReading": 82,
      "prep": 80
    }
  },
  {
    "id": "real_analyst_ynk",
    "name": "YNk",
    "role": "analyst",
    "level": 4,
    "specialization": "Opponent Prep",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Strategic breakdowns",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 87,
      "metaReading": 85,
      "prep": 88
    }
  }
];
