// Auto-generated by scripts/import-staff.js
import { StaffSaveData } from "./save-types";

export const LEGACY_STAFF_POOL: Partial<StaffSaveData>[] = [
  {
    "id": "staff_coach_zonix",
    "name": "Zonix",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 95,
      "development": 50,
      "leadership": 92
    }
  },
  {
    "id": "staff_coach_xyzt",
    "name": "Xyzt",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Sweden",
    "description": "Known for balanced play",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 90,
      "development": 50,
      "leadership": 88
    }
  },
  {
    "id": "staff_coach_scythe",
    "name": "Scythe",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Finland",
    "description": "Known for balanced play",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 88,
      "development": 50,
      "leadership": 86
    }
  },
  {
    "id": "staff_coach_vigil",
    "name": "Vigil",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Canada",
    "description": "Known for balanced play",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 85,
      "development": 50,
      "leadership": 84
    }
  },
  {
    "id": "staff_coach_garrick",
    "name": "Garrick",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 87,
      "development": 50,
      "leadership": 80
    }
  },
  {
    "id": "staff_coach_emir",
    "name": "Emir",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Known for balanced play",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "manManagement": 50,
      "tactical": 70,
      "development": 50,
      "leadership": 60
    }
  },
  {
    "id": "staff_coach_revin",
    "name": "Revin",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "manManagement": 50,
      "tactical": 72,
      "development": 50,
      "leadership": 58
    }
  },
  {
    "id": "staff_coach_kruzzz",
    "name": "Kruzzz",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 2500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "France",
    "description": "Known for balanced play",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "manManagement": 50,
      "tactical": 92,
      "development": 50,
      "leadership": 90
    }
  },
  {
    "id": "staff_coach_bl4dr",
    "name": "Bl4dr",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Ukraine",
    "description": "Known for balanced play",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 96,
      "development": 50,
      "leadership": 88
    }
  },
  {
    "id": "staff_coach_ronnik",
    "name": "Ronnik",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Sweden",
    "description": "Known for balanced play",
    "rarity": "Legendary",
    "salaryTier": "Very High",
    "stats": {
      "manManagement": 50,
      "tactical": 94,
      "development": 50,
      "leadership": 92
    }
  },
  {
    "id": "staff_coach_myther",
    "name": "Myther",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Known for balanced play",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 85,
      "development": 50,
      "leadership": 84
    }
  },
  {
    "id": "staff_coach_kasparr",
    "name": "Kasparr",
    "role": "coach",
    "level": 4,
    "specialization": "Tactical",
    "salaryPerWeek": 1500,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Known for balanced play",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "manManagement": 50,
      "tactical": 86,
      "development": 50,
      "leadership": 82
    }
  },
  {
    "id": "staff_analyst_spunk",
    "name": "Spunk",
    "role": "analyst",
    "level": 4,
    "specialization": "Macro & Meta",
    "salaryPerWeek": 2000,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Australia",
    "description": "Veteran analyst, ex-pro",
    "rarity": "Epic",
    "salaryTier": "High",
    "stats": {
      "analysis": 95,
      "metaReading": 94,
      "prep": 90
    }
  },
  {
    "id": "staff_analyst_thoran",
    "name": "Thoran",
    "role": "analyst",
    "level": 3,
    "specialization": "Narrative & History",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "UK",
    "description": "Esports journalism",
    "rarity": "Common",
    "salaryTier": "Low",
    "stats": {
      "analysis": 64,
      "metaReading": 45,
      "prep": 25
    }
  },
  {
    "id": "staff_analyst_morven",
    "name": "Morven",
    "role": "analyst",
    "level": 4,
    "specialization": "Strategy",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "USA",
    "description": "Tactical casting",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 88,
      "metaReading": 86,
      "prep": 84
    }
  },
  {
    "id": "staff_analyst_senner",
    "name": "Senner",
    "role": "analyst",
    "level": 4,
    "specialization": "Macro Analysis",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Denmark",
    "description": "Veteran analyst",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 85,
      "metaReading": 82,
      "prep": 80
    }
  },
  {
    "id": "staff_analyst_ymk",
    "name": "YMK",
    "role": "analyst",
    "level": 4,
    "specialization": "Opponent Prep",
    "salaryPerWeek": 1200,
    "teamId": undefined,
    "yearsRemaining": 1,
    "nationality": "Serbia",
    "description": "Strategic breakdowns",
    "rarity": "Rare",
    "salaryTier": "Medium",
    "stats": {
      "analysis": 87,
      "metaReading": 85,
      "prep": 88
    }
  }
];
