const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const EXCEL_PATH = path.join(process.cwd(), 'public/assets/staff/Esport_Manager_Staff_Market_Expanded (1).xlsx');
const COACH_IMG_DIR = path.join(process.cwd(), 'public/assets/staff/coaches');
const ANALYST_IMG_DIR = path.join(process.cwd(), 'public/assets/staff/analysts');
const OUTPUT_PATH = path.join(process.cwd(), 'engine/staff-db.ts');

function findImage(name, dir) {
    // Try exact match or sanitizing
    const safeName = name.replace(/\s+/g, '_');
    const files = fs.readdirSync(dir);

    // Exact match png
    let match = files.find(f => f.toLowerCase() === `${name.toLowerCase()}.png`);
    if (match) return `/assets/staff/coaches/${match}`; // Assuming both in same public struct or adjust

    // Partial?
    match = files.find(f => f.toLowerCase().includes(name.toLowerCase()));

    if (match) {
        // Fix path based on dir
        const relativeDir = dir.includes('coaches') ? 'coaches' : 'analysts';
        return `/assets/staff/${relativeDir}/${match}`;
    }

    return null;
}

try {
    const workbook = XLSX.readFile(EXCEL_PATH);
    const coaches = XLSX.utils.sheet_to_json(workbook.Sheets['Coaches']);
    const analysts = XLSX.utils.sheet_to_json(workbook.Sheets['Analysts']);

    const realStaffPool = [];

    // Process Coaches
    coaches.forEach(c => {
        if (!c.name) return;
        const img = findImage(c.name, COACH_IMG_DIR);
        const rarity = c.rarity || "Common";

        // Calculate Base Salary based on Tier if not explicit
        let salary = 1000;
        if (c.salary_tier === "Legendary") salary = 5000;
        else if (c.salary_tier === "Epic") salary = 3000;
        else if (c.salary_tier === "High") salary = 2500;
        else if (c.salary_tier === "Medium") salary = 1500;

        realStaffPool.push({
            id: `real_coach_${c.name.toLowerCase().replace(/[\s\.]/g, '_')}`,
            name: c.name,
            role: 'coach',
            level: Math.floor((c.overall_rating || 80) / 20),
            specialization: c.specialization || "Tactical",
            salaryPerWeek: salary,
            teamId: null,
            yearsRemaining: 1,
            nationality: c.nationality,
            description: c.reputation_notes || `Known for ${c.playstyle || 'balanced play'}`,
            portraitPath: img,
            rarity: rarity,
            salaryTier: c.salary_tier || "Medium",
            stats: {
                manManagement: c.man_management || 50,
                tactical: c.tactical_knowledge || c.tactical_skill || 50,
                development: c.player_development || c.training_skill || 50,
                leadership: c.leadership_skill || 50
            }
        });
    });

    // Process Analysts
    analysts.forEach(c => {
        if (!c.name) return;
        const img = findImage(c.name, ANALYST_IMG_DIR);
        const rarity = c.rarity || "Common";

        let salary = 1200;
        if (c.salary_tier === "Legendary") salary = 4500;
        else if (c.salary_tier === "Epic") salary = 2800;
        else if (c.salary_tier === "High") salary = 2000;

        realStaffPool.push({
            id: `real_analyst_${c.name.toLowerCase().replace(/[\s\.]/g, '_')}`,
            name: c.name,
            role: 'analyst',
            level: Math.floor((c.analysis_skill || 80) / 20),
            specialization: c.primary_focus || "Data",
            salaryPerWeek: salary,
            teamId: null,
            yearsRemaining: 1,
            nationality: c.nationality,
            description: c.known_for || "Expert Analyst",
            portraitPath: img,
            rarity: rarity,
            salaryTier: c.salary_tier || "Medium",
            stats: {
                analysis: c.analysis_skill || 50,
                metaReading: c.meta_reading || 50,
                prep: c.opponent_prep || 50
            }
        });
    });

    const fileContent = `// Auto-generated by scripts/import-staff.js
import { StaffSaveData } from "./save-types";

export const REAL_STAFF_POOL: Partial<StaffSaveData>[] = ${JSON.stringify(realStaffPool, null, 2)};
`;

    fs.writeFileSync(OUTPUT_PATH, fileContent);
    console.log(`Successfully generated ${realStaffPool.length} staff entries in engine/staff-db.ts`);

} catch (err) {
    console.error("Import failed:", err);
}
